### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by CMargreitter** [drazen-petrov/SMArt#1]
Thanks for the great package!

Just spotted a typo in the README
`from SMArt.md import parse_top, parse_ff
ff_gr = parse_ff(gromos_ifp_file) # by default, format_type = 'gm'
ff_gm = parse_ff (gromacs_ff_itp_file, format_type = 'gm')

top_gr = parse_top(gromos_top_file) # by default, format_type = 'gm'
top_gm = parse_top(gromacs_top_file, format_type = 'gm')`

The default, according to the code is "gr".

**Comment by drazen-petrov** [comment]
Thanks for pointing this out.
I've fixed it
