### ISSUE TITLE
N-terminal un-capped residues

### ISSUE THREAD

**Issue by BelyaevaJuly** [drazen-petrov/SMArt#2]
Dear colleagues,

is it possible to use your tool to construct a hybrid topology/structure for alchemical calculations in Gromacs with an un-capped N-terminal residue? For an example, with N-terminal positively-charged Valine?

Thank you for your time!

**Comment by drazen-petrov** [comment]
Dear user,
it is possible to use the tool to prepare different perturbation topologies.
What would you like to perturbe the N-terminal valine into? Valine to some other residue? 
Or maybe from capped into uncapped terminus? If that's the case, you probably want to use this server to prepare topologies of uncapped termini:
http://vienna-ptm.univie.ac.at/

For sure, the two above examples and other perturbations are possible, but you need to define state A and state B or your perturbation - peractically, this would be preparing 2 topologies which would be input for preparing the perturbation topology (as shown in the documentation page):
https://drazen-petrov.github.io/SMArt/Tutorial/perturbation_topologies.html

**Comment by BelyaevaJuly** [comment]
> What would you like to perturbe the N-terminal valine into? Valine to some other residue?
Or maybe from capped into uncapped terminus? If that's the case, you probably want to use this server to prepare topologies of uncapped termini

Dear Dr. Petrov, 

I would like to perturbe the uncapped N-terminal Val (positively charged) into uncapped N-terminal Ala (positively charged)

**Comment by drazen-petrov** [comment]
to do that you would need to make a topology starting with Val and an another topology starting with Ala
then you use these 2 topology files as an input to generate a perturbation topology as described here:
https://drazen-petrov.github.io/SMArt/Tutorial/perturbation_topologies.html

**Comment by BelyaevaJuly** [comment]
> to do that you would need to make a topology starting with Val and an another topology starting with Ala then you use these 2 topology files as an input to generate a perturbation topology as described here: https://drazen-petrov.github.io/SMArt/Tutorial/perturbation_topologies.html

Thank you for your help and your time!
